from astral import LocationInfo
import numpy as np

default_locInfo = LocationInfo("Croisic", "France", "Europe/London", 47.273, -2.516)

#Note : compute_title is useless for the moment
default_params = {
    "2DH" : {
        "typ" : "2DH",
        "same_ax" : False,
        "same_fig" : True,
        "video" : False,
        "X" : "X_KM",
        "Y" : "Y_KM",
        "plot_LAT_LON" : True,
        "plot_LANDMASK" : True,
        "plot_inner_doms" : False,
        "kwargs_plt" : {},
        "compute_title" : True,
        "savefig" : False,
        "plot_cbar" : True,
        "LiDAR" : True,
        "PARC" : False,
        "mesh" : True,
    },
    "2DV" : {
        "typ" : "2DV",
        "same_ax" : False,
        "same_fig" : True,
        "video" : False,
        "kwargs_get_data" : {
            "vinterp" : {},
        },
        "kwargs_plt" : {},
        "compute_title" : True,
        "savefig" : False,
        "plot_landsea" : True,
        "plot_cbar" : True,
        "mesh" : True,
    },
    "ZT" : {
        "typ" : "ZT",
        "Y" : "Z",
        "same_ax" : False,
        "same_fig" : True,
        "video" : False,
        "kwargs_plt" : {},
        "compute_title" : True,
        "savefig" : False,
        "plot_nighttime" : True,
        "plot_cbar" : True,
        "mesh" : True,
    },
    "2D" : {
        "typ" : "2D",
        "same_ax" : False,
        "same_fig" : True,
        "video" : False,
        "kwargs_plt" : {},
        "compute_title" : True,
        "savefig" : False,
        "plot_nighttime" : False,
        "plot_cbar" : True,
        "mesh" : True,
    },
    "1D" : {
        "typ" : "1D",
        "same_ax" : False,
        "same_fig" : True,
        "video" : False,
        "kwargs_plt" : {},
        "compute_title" : True,
        "savefig" : False,
        "grid" : True,
    },
    "SCATTER" : {
        "typ" : "SCATTER",
        "same_ax" : False,
        "same_fig" : True,
        "video" : False,
        "kwargs_plt" : {
            "cmap" : "Spectral_r",
            "edgecolor" : "k", 
            "linewidth" : .5
        },
        "compute_title" : True,
        "savefig" : False,
        "grid" : True,
        "plot_cbar" : True,
    },
    "RECTANGLE" : {
        "typ" : "RECTANGLE",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "Xname" : "X_KM",
        "Yname" : "Y_KM",
        "kwargs_plt" : {
            "edgecolor" : "k",
            "linewidth" : 1,
            "facecolor" : "none",
            "zorder" : 100, # Remove this if you want to draw something above the rectangle
        },
        "compute_title" : True,
        "savefig" : False,
        "animate" : False,
    },
    "CONTOUR" : {
        "typ" : "CONTOUR",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "kwargs_plt" : {
            "linewidths" : 1,
            "colors" : "k",
        },
        "X" : {"get" : ["same X", "dom X_KM"]},
        "Y" : {"get" : ["same Y", "dom Y_KM"]},
        "Z" : {"get" : ["same Z"]},
        "clabel" : True,
        "compute_title" : True,
        "savefig" : False,
    },
    "MASK" : {
        "typ" : "MASK",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "kwargs_plt" : {
            "linewidths" : 1,
            "colors" : "k",
            "levels" : [0.5]
        },
        "X" : {"get" : ["same X", "dom X_KM"]},
        "Y" : {"get" : ["same Y", "dom Y_KM"]},
        "Z" : {"get" : ["same Z"]},
        "clabel" : False,
        "compute_title" : False,
        "savefig" : False,
    },
    "LINE" : {
        "typ" : "LINE",
        "Xname" : "X_KM",
        "Yname" : "Y_KM",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "kwargs_plt" : {
            "color" : "k",
            "linewidth" : 2,
        },
        "kwargs_1" : {
            "marker" : "x",
        },
        "compute_title" : False,
        "savefig" : False,
        "animate" : False,
    },
    "LAT" : {
        "typ" : "LAT",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "X" : {"get" : ["same X", "dom X_KM"]},
        "Y" : {"get" : ["same Y", "dom Y_KM"]},
        "Z" : {"get" : ["same LAT",  "dom LAT"]},
        "kwargs_plt" : {
            "colors" : "gray",
            "linewidths" : 0.5,
        },
        "fontsize" : 10,
        "clabel" : True,
        "compute_title" : False,
        "savefig" : False,
        "animate" : False,
    },
    "LON" : {
        "typ" : "LON",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "X" : {"get" : ["same X", "dom X_KM"]},
        "Y" : {"get" : ["same Y", "dom Y_KM"]},
        "Z" : {"get" : ["same LON", "dom LON"]},
        "kwargs_plt" : {
            "colors" : "gray",
            "linewidths" : 0.5,
        },
        "fontsize" : 10,
        "clabel" : True,
        "compute_title" : False,
        "savefig" : False,
        "animate" : False,
    },
    "LANDMASK" : {
        "typ" : "LANDMASK",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "X" : {"get" : ["same X", "dom X_KM"]},
        "Y" : {"get" : ["same Y", "dom Y_KM"]},
        "Z" : {"get" : ["same LANDMASK", "dom LANDMASK"]},
        "kwargs_plt" : {
            "colors" : "k",
            "linewidths" : 1,
            "levels" : [0.5],
        },
        "clabel" : False,
        "compute_title" : False,
        "savefig" : False,
        "animate" : False,
    },
    "QUIVER" : {
        "typ" : "QUIVER",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "X" : {"get" : ["same X", "dom X_KM"]},
        "Y" : {"get" : ["same Y", "dom Y_KM"]},
        "U" : "U",
        "V" : "V",
        "kwargs_plt" : { #https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.quiver.html
            "color" : "w",
            "width" : 0.002,
            "headwidth" : 6,
            "pivot" : "mid",
            "scale" : 120, #scale velocities with a constant factor
            #-- For UW plots in 2DV cross section (works only if "X" and "Y" have the same units (meters or km))
            # "scale_units" : "xy", 
            # "angles" : "xy",
            # "scale" : 5,
        },
        "args_key" : [5, "5 m/s"],
        "size" : 1,
        "compute_title" : True,
        "savefig" : False,
        "step" : 18,
        "stepx": None,
        "plot_legend" : True,
    },
    "BARBS" : {
        "typ" : "BARBS",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "X" : {"get" : ["same X", "dom X_KM"]},
        "Y" : {"get" : ["same Y", "dom Y_KM"]},
        "U" : "U",
        "V" : "V",
        "kwargs_plt" : {
            "length" : 7,
            "pivot" : "mid",
        },
        "size" : 1,
        "compute_title" : True,
        "savefig" : False,
        "step" : 18,
        "stepx": None,
    },
    "UV" : {
        "typ" : "UV",
        "same_ax" : False,
        "same_fig" : True,
        "video" : False,
        "U" : "U",
        "V" : "V",
        "style" : "--",
        "kwargs_plt" : {
            "color" : 'k', 
        },
        "compute_title" : True,
        "savefig" : False,
        "NZ" : 15,
        "grid" : True,
    },
    "UV2" : {
        "typ" : "UV",
        "same_ax" : False,
        "same_fig" : True,
        "video" : False,
        "U" : "U",
        "V" : "V",
        "style" : "-",
        "kwargs_plt" : {
            "linewidth" : 2, 
        },
        "compute_title" : True,
        "savefig" : False,
        "NZ" : 1000,
        "grid" : True,
    },
    "NIGHTTIME" : {
        "typ" : "NIGHTTIME",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "locInfo" : default_locInfo,
        "X" : {"get" : ["same X", "dom TIME"]},
        "fac" : 0.04,
        "kwargs_plt_night" : {
            "color" : 'midnightblue',
            "alpha" : 1,
            "zorder" : 0,
        },
        "kwargs_plt_day" : {
            "color" : [0.8, 0.8, 0],
            "alpha" : 1,
            "zorder" : 0,
        },
        "savefig" : False,
    },
    "LANDSEA" : {
        "typ" : "LANDSEA",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "locInfo" : default_locInfo,
        "X" : {"get" : ["same X"]},
        "fac" : 0.01,
        "animate" : False,
        "kwargs_plt_land" : {
            "color" : [1, 1, 1],
            "alpha" : 1,
            "zorder" : 0,
        },
        "kwargs_plt_sea" : {
            "color" : [0, 0, 0],
            "alpha" : 1,
            "zorder" : 0,
        },
        "savefig" : False,
    },
    "WDH" : {
        "typ" : "WDH",
        "same_ax" : False,
        "same_fig" : True,
        "video" : False,
        "X" : "WD",
        "kwargs_plt" : {
            "bins" : 36, 
            "range" : (0, 2 * np.pi),
            "color" : 'skyblue', 
            "edgecolor" : 'black',
        },
        "compute_title" : True,
        "savefig" : False,
        "grid" : True,
    },
    "DATE" : {
        "typ" : "DATE",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "x" : "left",
        "y" : "top",
        "Z" : {"get" : ["same TIME", "dom TIME"]},
        "kwargs_plt" : {
            "color" : 'k', 
            "weight" : 'bold',
            "fontsize" : 25,
        },
        "compute_title" : False,
        "savefig" : False,
    },
    "TEXT" : {
        "typ" : "TEXT",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "x" : "left",
        "y" : "top",
        "kwargs_plt" : {
            "color" : 'k', 
            "weight" : 'bold',
            "fontsize" : 20,
        },
        "compute_title" : False,
        "savefig" : False,
    },
    "AXVLINE" : {
        "typ" : "AXVLINE",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "animate" : False,
        "X" : 0,
        "kwargs_plt" : {
            "color" : 'k', 
            "linewidth" : 1,
        },
        "compute_title" : False,
        "savefig" : False,
    },
    "AXHLINE" : {
        "typ" : "AXHLINE",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "animate" : False,
        "Y" : 0,
        "kwargs_plt" : {
            "color" : 'k', 
            "linewidth" : 1,
        },
        "compute_title" : False,
        "savefig" : False,
    },
    "AXVSPAN" : {
        "typ" : "AXVSPAN",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "animate" : False,
        "X1" : 0,
        "X2" : 1,
        "kwargs_plt" : {
            "facecolor" : 'grey', 
            "alpha" : 0.5,
        },
        "compute_title" : False,
        "savefig" : False,
    },
    "AXHSPAN" : {
        "typ" : "AXHSPAN",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "animate" : False,
        "Y1" : 0,
        "Y2" : 0,
        "kwargs_plt" : {
            "facecolor" : 'grey', 
            "alpha" : 0.5,
        },
        "compute_title" : False,
        "savefig" : False,
    },
    "POINT" : {
        "typ" : "POINT",
        "Xname" : "X_KM",
        "Yname" : "Y_KM",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "animate" : False,
        "style" : "+",
        "compute_title" : False,
        "savefig" : False,
        "grid" : False,
        "kwargs_plt" : {"markersize" : 20, "markeredgewidth" : 3},
    },
    "LiDAR" : {
        "typ" : "1D",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "animate" : False,
        "compute_title" : False,
        "savefig" : False,
        "grid" : False,
        "kwargs_plt" : {
            "color" : [0, 0.6, 0], 
            "linewidth" : 2,
        },
    },
    "PARC" : {
        "typ" : "1D",
        "same_ax" : True,
        "same_fig" : True,
        "video" : False,
        "animate" : False,
        "compute_title" : False,
        "savefig" : False,
        "grid" : False,
        "kwargs_plt" : {
            "color" : [0.3, 0.3, 0.3], 
            "linewidth" : 2,
        },
    },
}